version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 16-buster
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:redis

  redis:
    image: redislabs/rejson
    restart: unless-stopped